// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: omega/v1/omega.proto

package omegav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETED",
		4: "JOB_STATUS_FAILED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_COMPLETED":   3,
		"JOB_STATUS_FAILED":      4,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_omega_v1_omega_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_omega_v1_omega_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_omega_v1_omega_proto_rawDescGZIP(), []int{0}
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CircuitName   string                 `protobuf:"bytes,1,opt,name=circuit_name,json=circuitName,proto3" json:"circuit_name,omitempty"`
	Shots         int32                  `protobuf:"varint,2,opt,name=shots,proto3" json:"shots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_omega_v1_omega_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omega_v1_omega_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_omega_v1_omega_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetCircuitName() string {
	if x != nil {
		return x.CircuitName
	}
	return ""
}

func (x *SubmitJobRequest) GetShots() int32 {
	if x != nil {
		return x.Shots
	}
	return 0
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_omega_v1_omega_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omega_v1_omega_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_omega_v1_omega_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_omega_v1_omega_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omega_v1_omega_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_omega_v1_omega_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=omega.v1.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_omega_v1_omega_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omega_v1_omega_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_omega_v1_omega_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

var File_omega_v1_omega_proto protoreflect.FileDescriptor

const file_omega_v1_omega_proto_rawDesc = "" +
	"\n" +
	"\x14omega/v1/omega.proto\x12\bomega.v1\"K\n" +
	"\x10SubmitJobRequest\x12!\n" +
	"\fcircuit_name\x18\x01 \x01(\tR\vcircuitName\x12\x14\n" +
	"\x05shots\x18\x02 \x01(\x05R\x05shots\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"Z\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.omega.v1.JobStatusR\x06status*\x88\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x042\xa3\x01\n" +
	"\fOmegaService\x12D\n" +
	"\tSubmitJob\x12\x1a.omega.v1.SubmitJobRequest\x1a\x1b.omega.v1.SubmitJobResponse\x12M\n" +
	"\fGetJobStatus\x12\x1d.omega.v1.GetJobStatusRequest\x1a\x1e.omega.v1.GetJobStatusResponseB>Z<github.com/nishantapatil3/omega-apis/sdk/go/omega/v1;omegav1b\x06proto3"

var (
	file_omega_v1_omega_proto_rawDescOnce sync.Once
	file_omega_v1_omega_proto_rawDescData []byte
)

func file_omega_v1_omega_proto_rawDescGZIP() []byte {
	file_omega_v1_omega_proto_rawDescOnce.Do(func() {
		file_omega_v1_omega_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omega_v1_omega_proto_rawDesc), len(file_omega_v1_omega_proto_rawDesc)))
	})
	return file_omega_v1_omega_proto_rawDescData
}

var file_omega_v1_omega_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_omega_v1_omega_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_omega_v1_omega_proto_goTypes = []any{
	(JobStatus)(0),               // 0: omega.v1.JobStatus
	(*SubmitJobRequest)(nil),     // 1: omega.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),    // 2: omega.v1.SubmitJobResponse
	(*GetJobStatusRequest)(nil),  // 3: omega.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil), // 4: omega.v1.GetJobStatusResponse
}
var file_omega_v1_omega_proto_depIdxs = []int32{
	0, // 0: omega.v1.GetJobStatusResponse.status:type_name -> omega.v1.JobStatus
	1, // 1: omega.v1.OmegaService.SubmitJob:input_type -> omega.v1.SubmitJobRequest
	3, // 2: omega.v1.OmegaService.GetJobStatus:input_type -> omega.v1.GetJobStatusRequest
	2, // 3: omega.v1.OmegaService.SubmitJob:output_type -> omega.v1.SubmitJobResponse
	4, // 4: omega.v1.OmegaService.GetJobStatus:output_type -> omega.v1.GetJobStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_omega_v1_omega_proto_init() }
func file_omega_v1_omega_proto_init() {
	if File_omega_v1_omega_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omega_v1_omega_proto_rawDesc), len(file_omega_v1_omega_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_omega_v1_omega_proto_goTypes,
		DependencyIndexes: file_omega_v1_omega_proto_depIdxs,
		EnumInfos:         file_omega_v1_omega_proto_enumTypes,
		MessageInfos:      file_omega_v1_omega_proto_msgTypes,
	}.Build()
	File_omega_v1_omega_proto = out.File
	file_omega_v1_omega_proto_goTypes = nil
	file_omega_v1_omega_proto_depIdxs = nil
}
