# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omega/v1/omega.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'omega/v1/omega.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14omega/v1/omega.proto\x12\x08omega.v1\"7\n\x10SubmitJobRequest\x12\x14\n\x0c\x63ircuit_name\x18\x01 \x01(\t\x12\r\n\x05shots\x18\x02 \x01(\x05\"#\n\x11SubmitJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"%\n\x13GetJobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"K\n\x14GetJobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12#\n\x06status\x18\x02 \x01(\x0e\x32\x13.omega.v1.JobStatus*\x88\x01\n\tJobStatus\x12\x1a\n\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n\x12JOB_STATUS_RUNNING\x10\x02\x12\x18\n\x14JOB_STATUS_COMPLETED\x10\x03\x12\x15\n\x11JOB_STATUS_FAILED\x10\x04\x32\xa3\x01\n\x0cOmegaService\x12\x44\n\tSubmitJob\x12\x1a.omega.v1.SubmitJobRequest\x1a\x1b.omega.v1.SubmitJobResponse\x12M\n\x0cGetJobStatus\x12\x1d.omega.v1.GetJobStatusRequest\x1a\x1e.omega.v1.GetJobStatusResponseB>Z<github.com/nishantapatil3/omega-apis/sdk/go/omega/v1;omegav1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omega.v1.omega_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/nishantapatil3/omega-apis/sdk/go/omega/v1;omegav1'
  _globals['_JOBSTATUS']._serialized_start=245
  _globals['_JOBSTATUS']._serialized_end=381
  _globals['_SUBMITJOBREQUEST']._serialized_start=34
  _globals['_SUBMITJOBREQUEST']._serialized_end=89
  _globals['_SUBMITJOBRESPONSE']._serialized_start=91
  _globals['_SUBMITJOBRESPONSE']._serialized_end=126
  _globals['_GETJOBSTATUSREQUEST']._serialized_start=128
  _globals['_GETJOBSTATUSREQUEST']._serialized_end=165
  _globals['_GETJOBSTATUSRESPONSE']._serialized_start=167
  _globals['_GETJOBSTATUSRESPONSE']._serialized_end=242
  _globals['_OMEGASERVICE']._serialized_start=384
  _globals['_OMEGASERVICE']._serialized_end=547
# @@protoc_insertion_point(module_scope)
